#!/bin/bash
set -e

ln -s /usr/share/icons/hicolor/128x128/apps/tinymice.png /usr/share/pixmaps/tinymice.png
ln -s /usr/share/tinymice/tinymice /usr/bin/tinymice 
#chown root:root /usr/share/pixmaps/tinymice.png
#chown root:root /usr/bin/tinymice

echo "[Desktop Entry]" > /usr/share/applications/TinyMouse.desktop
echo "Name=TinyMice" >> /usr/share/applications/TinyMouse.desktop
echo "Comment=Auto Clicker" >> /usr/share/applications/TinyMouse.desktop
echo "Exec=tinymice" >> /usr/share/applications/TinyMouse.desktop
echo "Icon=tinymice" >> /usr/share/applications/TinyMouse.desktop
echo "Terminal=false" >> /usr/share/applications/TinyMouse.desktop
echo "Type=Application" >> /usr/share/applications/TinyMouse.desktop
echo "Categories=Utility;" >> /usr/share/applications/TinyMouse.desktop
echo "StartupNotify=true" >> /usr/share/applications/TinyMouse.desktop
echo "Keywords=Auto;Clicker;AutoClicker;Auto Clicker;Mouse;" >> /usr/share/applications/TinyMouse.desktop

chown root:root /usr/share/applications/TinyMouse.desktop
chmod 755 /usr/share/applications/TinyMouse.desktop

