#!/bin/bash
set -e

rm -f /usr/share/applications/TinyMouse.desktop
rm -f /usr/share/pixmaps/tinymice.png
rm -f /usr/bin/tinymice
rm -f /usr/share/icons/hicolor/128x128/apps/tinymice.png
rm -Rf /usr/share/tinymice

